## Preprocessing

In [38]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\ksarn\anaconda3\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.32.2)
Requirement already satisfied: setuptools in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (69.5.1)
Requirement already satisfied: six>=1.12.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.68.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.7.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.11.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\ksarn\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.43.0)
Requirement already satisfied: rich in c:\users\ksarn\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (13.3.5)
Requirement already satisfied: namex in c:\users\ksarn\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\ksarn\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ksarn\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ksarn\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ksarn\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ksarn\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\ksarn\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\ksarn\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\ksarn\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ksarn\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\ksarn\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [39]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [40]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [41]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [42]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
count_type = application_df['APPLICATION_TYPE'].value_counts()
count_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [43]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
#application_types_to_replace = count_type[count_type< 100].index.values
application_types_to_replace = list(count_type.iloc[4:].index)
cutoff_value = 500
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     3331
T4        1542
T6        1216
T5        1173
Name: count, dtype: int64

In [44]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
clasification_counts = application_df['CLASSIFICATION'].value_counts()
clasification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [45]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_v = clasification_counts.loc[clasification_counts > 1]
classification_v

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [46]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(classification_v.iloc[10:].index)
cutoff_value_classifications = 500
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      747
C1700      287
C4000      194
C5000      116
C1270      114
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [47]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
convert_dummies = pd.get_dummies(application_df)
convert_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,True,False,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [48]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = convert_dummies['IS_SUCCESSFUL'].values
X = convert_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y,stratify=y)

In [49]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [60]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 250
hidden_nodes_layer2 = 100
hidden_nodes_layer3 = 200
hidden_nodes_layer4= 100

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))
#  YOUR CODE GOES HERE

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Third hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(hidden_nodes_layer3, activation = "relu"))
# fourth layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(hidden_nodes_layer4, activation = "relu"))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_40 (Dense)                │ (None, 250)            │        17,750 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 100)            │        25,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 100)            │        20,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83,251 (325.20 KB)

 Trainable params: 83,251 (325.20 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [62]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 830us/step - accuracy: 0.6991 - loss: 0.5960
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 811us/step - accuracy: 0.7191 - loss: 0.5713
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7243 - loss: 0.5586
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 806us/step - accuracy: 0.7249 - loss: 0.5607
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7311 - loss: 0.5540
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 893us/step - accuracy: 0.7276 - loss: 0.5563
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7263 - loss: 0.5544
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 838us/step - accuracy: 0.7300 - loss: 0.5526
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - accuracy: 0.7323 - loss: 0.5519
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 810us/step - accuracy: 0.7296 - loss: 0.5551
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - accuracy: 0.7318 - loss: 0.5543
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 805us/step - accuracy: 0.7281 - loss: 0.5507
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 811us/step - accuracy: 0.7229 - loss: 0.5580
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.7271 - loss: 0.5580
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7275 - loss: 0.5561
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.7308 - loss: 0.5501
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.7291 - loss: 0.5532
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 785us/step - accuracy: 0.7326 - loss: 0.5493
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.7309 - loss: 0.5477
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7319 - loss: 0.5508
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 786us/step - accuracy: 0.7360 - loss: 0.5464
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.7313 - loss: 0.5502
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.7300 - loss: 0.5499
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7288 - loss: 0.5536
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 786us/step - accuracy: 0.7329 - loss: 0.5459
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.7341 - loss: 0.5483
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7291 - loss: 0.5526
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - accuracy: 0.7356 - loss: 0.5446
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 757us/step - accuracy: 0.7321 - loss: 0.5457
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.7315 - loss: 0.5476
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7250 - loss: 0.5530
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 810us/step - accuracy: 0.7324 - loss: 0.5479
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.7312 - loss: 0.5464
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 0.7275 - loss: 0.5486
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.7309 - loss: 0.5500
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.7368 - loss: 0.5404
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.7332 - loss: 0.5427
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.7315 - loss: 0.5475
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.7399 - loss: 0.5382
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 788us/step - accuracy: 0.7325 - loss: 0.5438
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.7272 - loss: 0.5516
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7320 - loss: 0.5449
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.7372 - loss: 0.5416
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 782us/step - accuracy: 0.7348 - loss: 0.5437
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7317 - loss: 0.5455
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.7332 - loss: 0.5430
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 763us/step - accuracy: 0.7310 - loss: 0.5488
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.7344 - loss: 0.5433
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 0.7371 - loss: 0.5434
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 793us/step - accuracy: 0.7324 - loss: 0.5430
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.7323 - loss: 0.5437
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7292 - loss: 0.5487
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.7313 - loss: 0.5477
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.7284 - loss: 0.5485
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.7357 - loss: 0.5419
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 763us/step - accuracy: 0.7365 - loss: 0.5432
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.7312 - loss: 0.5468
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 785us/step - accuracy: 0.7330 - loss: 0.5428
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - accuracy: 0.7388 - loss: 0.5384
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7351 - loss: 0.5397
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7310 - loss: 0.5436
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 785us/step - accuracy: 0.7278 - loss: 0.5476
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 787us/step - accuracy: 0.7322 - loss: 0.5462
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.7371 - loss: 0.5383
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 782us/step - accuracy: 0.7383 - loss: 0.5414
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7314 - loss: 0.5465
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.7394 - loss: 0.5364
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.7363 - loss: 0.5411
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7295 - loss: 0.5465
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7375 - loss: 0.5400
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 898us/step - accuracy: 0.7347 - loss: 0.5429
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - accuracy: 0.7367 - loss: 0.5398
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 835us/step - accuracy: 0.7360 - loss: 0.5398
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 831us/step - accuracy: 0.7351 - loss: 0.5406
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 804us/step - accuracy: 0.7355 - loss: 0.6377
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 869us/step - accuracy: 0.7321 - loss: 0.5443
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7322 - loss: 0.5421
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.7381 - loss: 0.5337
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - accuracy: 0.7344 - loss: 0.5406
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.7321 - loss: 0.5441
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - accuracy: 0.7355 - loss: 0.5391
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - accuracy: 0.7354 - loss: 0.5390
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 854us/step - accuracy: 0.7361 - loss: 0.5411
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - accuracy: 0.7349 - loss: 0.5396
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.7280 - loss: 0.5475
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7347 - loss: 0.5449
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.7331 - loss: 0.5643
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.7343 - loss: 0.5418
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7368 - loss: 0.5422
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 880us/step - accuracy: 0.7389 - loss: 0.5367
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7346 - loss: 0.5411
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7345 - loss: 0.5427
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7351 - loss: 0.5409
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 883us/step - accuracy: 0.7369 - loss: 0.5403
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 873us/step - accuracy: 0.7375 - loss: 0.5360
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 890us/step - accuracy: 0.7341 - loss: 0.5412
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - accuracy: 0.7397 - loss: 0.5387
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7349 - loss: 0.5430
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 941us/step - accuracy: 0.7360 - loss: 0.5393
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 941us/step - accuracy: 0.7318 - loss: 0.5432

In [63]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7291 - loss: 0.5932
Loss: 0.5932251214981079, Accuracy: 0.7290962338447571

In [54]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
#nn.save("AlphabetSoupCharity.h5")

nn.save("AlphabetSoupCharity_Optimization.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.